#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

# ##############################################################################
# #                                AUTOSTART APPS                              #
# ##############################################################################
xrdb -load ~/.Xresources
dunst --config $HOME/.config/dunst/dunstrc &
picom --config $HOME/.config/picom/picom.conf &
sh ~/.config/polybar/launch.sh
wal -i /home/zeriax/Pictures/wallpaper.jpg
mpd 
xsetroot -cursor_name left_ptr
setxkbmap -layout fi
xautolock -detectsleep -time 10 -locker "betterlockscreen -l dim" -notify 30 -notifier "dunstify -u critical -t 30 -- ' locking in 30 seconds!'" &

# ##############################################################################
# #                            GENERAL CONFIGURATION                           #
# ##############################################################################

bspc monitor -d I II III IV V VI VII VIII

bspc config border_width         2
bspc config window_gap           10

bspc config top_padding          60
bspc config bottom_padding       10
bspc config left_padding         10
bspc config right_padding         10


bspc config normal_border_color  "#2d3445"
bspc config active_border_color  "#5e516c"
bspc config focused_border_color "#b36288"

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# ##############################################################################
# #                                 WINDOW RULES                               #
# ##############################################################################

#bpsc rule -a kitty state=floating
# bpsc rule -a kitty desktop=^1
# bpsc rule -a Google-chrome desktop=^2
# bspc rule -a firefox desktop=^1
# bspc rule -a discord desktop=^4
# bspc rule -a sublime desktop=^3
# bspc rule -a spotify desktop=^6
